apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: donation-manager-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: boprisiu/cloudlab2-frontend:latest
          ports:
            - containerPort: 80