apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: donation-manager-namespace
data:
  SPRING_PROFILES_ACTIVE: "prod"
  APP_ENV: "production"
  LOG_LEVEL: "debug"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "donation_manager"
  DB_USER: "root"